import { GoogleGenAI, Type } from "@google/genai";
import { safeStringify } from "./firebase";

let aiInstance: GoogleGenAI | null = null;

function getAI() {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
      throw new Error("GEMINI_API_KEY is not configured in the environment.");
    }
    aiInstance = new GoogleGenAI({ apiKey });
  }
  return aiInstance;
}

export interface StudentReport {
  performanceSummary: string;
  parentFeedback: string;
}

/**
 * Generates an AI-powered student performance report.
 * @param studentData - The data object containing student information, grades, etc.
 * @returns A promise that resolves to a StudentReport object.
 */
export async function generateStudentReport(studentData: any): Promise<StudentReport> {
  const prompt = `
    Analyze the following student data and generate a comprehensive performance report:
    ${safeStringify(studentData, 2)}
  `;

  try {
    const ai = getAI();
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        systemInstruction: "You are an expert academic counselor at Nexus Academy. Your role is to analyze student data and provide insights. Create a performance summary that highlights key strengths and growth areas, and write a professional, empathetic message for parents that offers actionable suggestions for support at home.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            performanceSummary: {
              type: Type.STRING,
              description: "A detailed but concise summary of academic and behavioral performance."
            },
            parentFeedback: {
              type: Type.STRING,
              description: "A personalized, constructive message for the student's parents or guardians."
            }
          },
          required: ["performanceSummary", "parentFeedback"]
        }
      }
    });

    const result = response.text;
    if (!result) {
      throw new Error("No report content generated by the AI model.");
    }

    return JSON.parse(result.trim());
  } catch (error) {
    console.error("AI Report Generation Error:", error);
    throw error;
  }
}

/**
 * Transforms raw notes into a professional social media post.
 */
export async function generateSocialPost(notes: string): Promise<string> {
  const prompt = `
    Transform the following raw notes into a professional, engaging, and inspiring social media post for a school (Nexus Academy).
    Include appropriate emojis and formatting. Keep it concise but impactful.
    
    Notes: ${notes}
  `;

  try {
    const ai = getAI();
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        systemInstruction: "You are a creative social media manager for Nexus Academy. Your tone is professional, enthusiastic, and community-focused. You specialize in taking brief notes and expanding them into compelling narratives for school updates.",
      }
    });

    return response.text?.trim() || "Failed to generate post.";
  } catch (error) {
    console.error("AI Post Generation Error:", error);
    throw error;
  }
}
